name: Double Signing Global L0 Cluster

inputs:
  RUN_ROLLBACK:
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Double Signing L0 Genesis
      with:
        CL_PUBLIC_HTTP_PORT: 9000
        CL_P2P_HTTP_PORT: 9001
        CL_CLI_HTTP_PORT: 9002
        RUN_ROLLBACK: ${{ inputs.RUN_ROLLBACK }}
      uses: "./.github/templates/attack/rollback/genesis"

    - name: Run Double Signing L0 Validator - 1
      uses: "./.github/templates/attack/rollback/validator"
      with:
        CL_PUBLIC_HTTP_PORT: 8000
        CL_P2P_HTTP_PORT: 8001
        CL_CLI_HTTP_PORT: 8002
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_P2P_HTTP_PORT: 9001
        NODE_NUMBER: 1

    - name: Run Double Signing L0 Validator - 2
      uses: "./.github/templates/attack/rollback/validator"
      with:
        CL_PUBLIC_HTTP_PORT: 8100
        CL_P2P_HTTP_PORT: 8101
        CL_CLI_HTTP_PORT: 8102
        CL_GLOBAL_L0_PEER_HTTP_PORT: 9000
        CL_L0_P2P_HTTP_PORT: 9001
        NODE_NUMBER: 2